### ISSUE TITLE
Feature Request: Bid vs Ask prices

### ISSUE THREAD

**Issue by orestesgaolin** [korasinski/ha-nbp#1]
It would be awesome to be able to query for Bid and Ask prices (kupno/sprzedaż). 

For instance these could be my desired configuration options:

```
sensor:
  - platform: nbp
    scan_interval: 00:60:00
    currency:
      - code: USD
        name: USD to PLN
        type: BID
      - code: EUR
        name: EUR to PLN
        type: ASK
```

**Comment by orestesgaolin** [comment]
Solution 

configuration.yaml

```yaml
sensor:
  - platform: nbp
    scan_interval: 00:60:00
    currency:
      - code: USD
        name: "USD to PLN"
      - code: EUR
        name: "EUR to PLN"
  - platform: template
    sensors:
      usd_to_pln_bid:
        friendly_name: "USD to PLN bid"
        value_template: "{{ state_attr('sensor.usd_to_pln', 'bid') }}"
```

<img width="945" alt="CleanShot 2022-07-06 at 11 09 07@2x" src="https://user-images.githubusercontent.com/16854239/177514363-7fc2e1c4-36dc-4bd7-afb2-1b82cccee946.png">
